const homeDays = ["domingo", "segunda-feira", "terça-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sábado"];
function homeEscape(value) { const node = document.createElement("div"); node.textContent = value || ""; return node.innerHTML; }
function homeRecurrence(item) { if (item.recorrencia === "semanal") return homeDays[item.dia_semana]; if (item.recorrencia === "mensal") return `${item.semana_mes}${[0,6].includes(item.dia_semana)?"º":"ª"} ${homeDays[item.dia_semana]} do mês`; if (item.recorrencia === "data_especifica") return new Date(`${item.data_especifica}T12:00:00`).toLocaleDateString("pt-BR"); return item.recorrencia_texto; }
function nextOccurrence(item) { const now=new Date(),[hour,minute]=item.horario.split(":").map(Number); if(item.recorrencia==="data_especifica")return new Date(`${item.data_especifica}T${item.horario}:00`); if(item.recorrencia==="semanal"){const date=new Date(now);let add=(item.dia_semana-now.getDay()+7)%7;date.setDate(now.getDate()+add);date.setHours(hour,minute,0,0);if(date<now)date.setDate(date.getDate()+7);return date} if(item.recorrencia==="mensal"){for(let offset=0;offset<2;offset++){const first=new Date(now.getFullYear(),now.getMonth()+offset,1,hour,minute);const add=(item.dia_semana-first.getDay()+7)%7+(item.semana_mes-1)*7;first.setDate(1+add);if(first>=now)return first}}return new Date(now.getTime()+90*86400000); }
async function loadHomeContent() {
  const schedules = document.getElementById("home-programacoes"); const notices = document.getElementById("home-avisos");
  try { const response = await fetch("/api/programacoes"); const data = await response.json(); if (!response.ok) throw new Error(); const communities = new Map(data.comunidades.map((item) => [item.id,item.nome])); const items = data.programacoes.slice().sort((a,b) => nextOccurrence(a)-nextOccurrence(b)).slice(0,4); schedules.innerHTML = items.map((item) => `<article class="quick-link"><strong>${homeEscape(item.atividade)} · ${homeEscape(item.horario.replace(":","h"))}</strong><span>${homeEscape(homeRecurrence(item))}<br>${homeEscape(communities.get(item.comunidade_id))}</span></article>`).join("") || '<p class="home-empty">Programação em atualização.</p>'; } catch { schedules.innerHTML = '<p class="home-empty">Consulte a programação completa para ver os horários.</p>'; }
  try { const response = await fetch("/api/avisos"); const data = await response.json(); if (!response.ok) throw new Error(); notices.innerHTML = data.avisos.slice(0,3).map((item) => `<article class="quick-link"><strong>${homeEscape(item.titulo)}</strong><span>${homeEscape(item.descricao.slice(0,110))}${item.descricao.length>110?"…":""}</span></article>`).join("") || '<p class="home-empty">Não há avisos no momento.</p>'; } catch { notices.innerHTML = '<p class="home-empty">Não foi possível carregar os avisos.</p>'; }
}
loadHomeContent();
